name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */4 * * *' # Rulează la fiecare 4 ore
  workflow_dispatch: # Îți permite să îl pornești și manual

jobs:
  ping-app:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I https://predict-a9g9znwhduuvcawstsiex6.streamlit.app/
